# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9326e4cbf65b53fa73aaab06ac04b10db1f2b68e6737cc4456cff9942601c51900217d50cc245cc8e41ea970092821a6ec9ffefb4bc21a4f195c550b421ac03

test:
  secret_key_base: 282cae7537e5b4377da6d998c7c169ba1b868eb3398640bd0cc9af98a0fac151ed41705172354c3e9da3caebe5dcc4f6a01f80426c0bdc637ee03ff6c581d5a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
